name: Continuous Development

on:
  push:
    branches:
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy staging
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          # password: ${{ secrets.SSH_PASSWORD }}
          # passphrase: ${{secrets.SSH_PASSPHRASE}}
          key: ${{secrets.SSH_KEY}}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/vkpads/laravel-test-ci-cd
            git pull origin staging
            docker-compose down app
            docker-compose up -d app
