name: Continuous Development

on:
  push:
    branches:
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          repository: ${{secrets.GIT_REPO}}
          token: ${{secrets.GIT_TOKEN}}
          script: |
            cd /home/vkpads/laravel-test-ci-cd
            git pull origin staging
            sudo docker-compose down app
            sudo docker-compose up -d app
