name: Continuous Integration

on:
  push:
    branches:
      - staging

jobs:
  test:
    name: Deploy Staging
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy staging
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          # password: ${{ secrets.SSH_PASSWORD }}
          # passphrase: ${{secrets.SSH_PASSPHRASE}}
          key: ${{secrets.SSH_KEY}}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            cd /home/vkpads/laravel-test-ci-cd
            git pull origin staging
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install --lts
            npm run build
            sudo docker exec ads-app bash -c "composer install"
            sudo docker exec ads-app bash -c "php artisan migrate"
            sudo docker exec ads-app bash -c "php artisan optimize"
